# Generated by Django 6.0.2 on 2026-02-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bata_app', '0002_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variant_images/')),
                ('is_main', models.BooleanField(default=False, help_text='Main image for this variant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bata_app.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductColorImage',
        ),
    ]
